In [1]:
import torch

In [15]:
#tensor数据类型
#生成tensor
#(1)torch.FloatTensor用于生成浮点数据类型的tensor，参数可以使shape或list
#a=torch.FloatTensor(3,3)#都是随机数
#b=torch.FloatTensor([1,2,3,4,5])

#(2)torch.
#torch.IntTensor用于生成整形数据类型的tensor，参数同上
#a=torch.IntTensor(5,2)
#b=torch.IntTensor([9,8,7,6,5])

#(3)torch.rand()生成浮点型指定shape的0-1之间的随机数
#a=torch.rand(3,3)

#(4）torch.randn()生成浮点型指定shape，均值为0，方差为1的正态分布tensor
#a=torch.randn(3,3)

#(5)torch.range(1,20,1)生成1到20步长为1的数据
#a=torch.range(1,20,1)

#(6)
#a=torch.zeros(2,2)
print(a)
#print(b)

tensor([[0., 0.],
        [0., 0.]])


In [21]:
#tensor运算
#(1)torch.abs()求绝对值
#(2)torch.add()参数为两个tensor或一个tensor一个标量
#a=torch.randn(3,3)
#print(a)

#b=torch.randn(3,3)
#print(b)

#c=torch.add(a,b)
#print(c)

#d=torch.add(c,10)
#print(d)
#(3)torch.clamp()：裁剪数据
#a=torch.randn(3,3)
#b=torch.clamp(a,-0.1,0.1)#参数：原tensor，下边界，上边界
#print(a)
#print(b)

#(4)torch.div()：tensor相除，参数类似torch.add()
#(5)torch.mul()：tensor求积，参数类似torch.add()
#torch.pow(a,3)求幂运算
#b=torch.pow(a,3)
#print(b)

#(6)矩阵相乘torch.mm()
#(7)矩阵乘向量torch.mv(),参数为矩阵和向量，且向量的长度必须等于矩阵的列数
a=torch.randn(3,2)
b=torch.randn(2,3)
c=torch.mm(a,b)
d=torch.randn(3)
e=torch.mv(c,d)
print(c)
print(e)

tensor([[ 0.8174,  0.1594, -0.6060],
        [-0.9087, -0.3939,  0.7999],
        [ 0.0108,  1.3771, -0.8093]])
tensor([ 1.6805, -2.5409,  4.2905])


In [ ]:
#输入特征：1000，隐藏层：100，输出层：10，batch_size=100